// Code generated by protoc-gen-go. DO NOT EDIT.
// source: primeNumberDecomposition.proto

package primeNumberDecomposition

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PrimeNumberDecomposition struct {
	Num                  int32    `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNumberDecomposition) Reset()         { *m = PrimeNumberDecomposition{} }
func (m *PrimeNumberDecomposition) String() string { return proto.CompactTextString(m) }
func (*PrimeNumberDecomposition) ProtoMessage()    {}
func (*PrimeNumberDecomposition) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa651d2a397d2699, []int{0}
}

func (m *PrimeNumberDecomposition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNumberDecomposition.Unmarshal(m, b)
}
func (m *PrimeNumberDecomposition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNumberDecomposition.Marshal(b, m, deterministic)
}
func (m *PrimeNumberDecomposition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNumberDecomposition.Merge(m, src)
}
func (m *PrimeNumberDecomposition) XXX_Size() int {
	return xxx_messageInfo_PrimeNumberDecomposition.Size(m)
}
func (m *PrimeNumberDecomposition) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNumberDecomposition.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNumberDecomposition proto.InternalMessageInfo

func (m *PrimeNumberDecomposition) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

type PrimeNumberDecompositionRequest struct {
	PrimeNumberDecomposition *PrimeNumberDecomposition `protobuf:"bytes,1,opt,name=primeNumberDecomposition,proto3" json:"primeNumberDecomposition,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                  `json:"-"`
	XXX_unrecognized         []byte                    `json:"-"`
	XXX_sizecache            int32                     `json:"-"`
}

func (m *PrimeNumberDecompositionRequest) Reset()         { *m = PrimeNumberDecompositionRequest{} }
func (m *PrimeNumberDecompositionRequest) String() string { return proto.CompactTextString(m) }
func (*PrimeNumberDecompositionRequest) ProtoMessage()    {}
func (*PrimeNumberDecompositionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa651d2a397d2699, []int{1}
}

func (m *PrimeNumberDecompositionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNumberDecompositionRequest.Unmarshal(m, b)
}
func (m *PrimeNumberDecompositionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNumberDecompositionRequest.Marshal(b, m, deterministic)
}
func (m *PrimeNumberDecompositionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNumberDecompositionRequest.Merge(m, src)
}
func (m *PrimeNumberDecompositionRequest) XXX_Size() int {
	return xxx_messageInfo_PrimeNumberDecompositionRequest.Size(m)
}
func (m *PrimeNumberDecompositionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNumberDecompositionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNumberDecompositionRequest proto.InternalMessageInfo

func (m *PrimeNumberDecompositionRequest) GetPrimeNumberDecomposition() *PrimeNumberDecomposition {
	if m != nil {
		return m.PrimeNumberDecomposition
	}
	return nil
}

type PrimeNumberDecompositionResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNumberDecompositionResponse) Reset()         { *m = PrimeNumberDecompositionResponse{} }
func (m *PrimeNumberDecompositionResponse) String() string { return proto.CompactTextString(m) }
func (*PrimeNumberDecompositionResponse) ProtoMessage()    {}
func (*PrimeNumberDecompositionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa651d2a397d2699, []int{2}
}

func (m *PrimeNumberDecompositionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNumberDecompositionResponse.Unmarshal(m, b)
}
func (m *PrimeNumberDecompositionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNumberDecompositionResponse.Marshal(b, m, deterministic)
}
func (m *PrimeNumberDecompositionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNumberDecompositionResponse.Merge(m, src)
}
func (m *PrimeNumberDecompositionResponse) XXX_Size() int {
	return xxx_messageInfo_PrimeNumberDecompositionResponse.Size(m)
}
func (m *PrimeNumberDecompositionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNumberDecompositionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNumberDecompositionResponse proto.InternalMessageInfo

func (m *PrimeNumberDecompositionResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*PrimeNumberDecomposition)(nil), "primeNumberDecomposition.PrimeNumberDecomposition")
	proto.RegisterType((*PrimeNumberDecompositionRequest)(nil), "primeNumberDecomposition.PrimeNumberDecompositionRequest")
	proto.RegisterType((*PrimeNumberDecompositionResponse)(nil), "primeNumberDecomposition.PrimeNumberDecompositionResponse")
}

func init() { proto.RegisterFile("primeNumberDecomposition.proto", fileDescriptor_fa651d2a397d2699) }

var fileDescriptor_fa651d2a397d2699 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2b, 0x28, 0xca, 0xcc,
	0x4d, 0xf5, 0x2b, 0xcd, 0x4d, 0x4a, 0x2d, 0x72, 0x49, 0x4d, 0xce, 0xcf, 0x2d, 0xc8, 0x2f, 0xce,
	0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0xc0, 0x25, 0xaf, 0xa4,
	0xc3, 0x25, 0x11, 0x80, 0x43, 0x4e, 0x48, 0x80, 0x8b, 0x39, 0xaf, 0x34, 0x57, 0x82, 0x51, 0x81,
	0x51, 0x83, 0x35, 0x08, 0xc4, 0x54, 0x9a, 0xc8, 0xc8, 0x25, 0x8f, 0x4b, 0x79, 0x50, 0x6a, 0x61,
	0x69, 0x6a, 0x71, 0x89, 0x50, 0x1e, 0x17, 0x4e, 0xdb, 0xc0, 0x46, 0x71, 0x1b, 0x19, 0xe9, 0xe1,
	0x74, 0x2e, 0x4e, 0xc3, 0x71, 0xfb, 0xc0, 0x8a, 0x4b, 0x01, 0xb7, 0x93, 0x8a, 0x0b, 0xf2, 0xf3,
	0x8a, 0x53, 0x85, 0xc4, 0xb8, 0xd8, 0x8a, 0x52, 0x8b, 0x4b, 0x73, 0x4a, 0xa0, 0x9e, 0x81, 0xf2,
	0x8c, 0xf6, 0xe3, 0xf1, 0x4f, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0xd0, 0x6c, 0x46, 0x2e,
	0x39, 0x9c, 0x6a, 0x4a, 0x8a, 0x52, 0x13, 0x73, 0x85, 0x2c, 0xc9, 0xf0, 0x10, 0x24, 0xb4, 0xa4,
	0xac, 0xc8, 0xd1, 0x0a, 0xf1, 0x95, 0x12, 0x83, 0x01, 0xa3, 0x93, 0x54, 0x14, 0xce, 0x90, 0x49,
	0x62, 0x03, 0x47, 0xbe, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x88, 0x65, 0xd2, 0x3e, 0x1e, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PrimeNumberDecompositionServiceClient is the client API for PrimeNumberDecompositionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrimeNumberDecompositionServiceClient interface {
	//server streaming
	PrimeNumberDecompositionStream(ctx context.Context, in *PrimeNumberDecompositionRequest, opts ...grpc.CallOption) (PrimeNumberDecompositionService_PrimeNumberDecompositionStreamClient, error)
}

type primeNumberDecompositionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrimeNumberDecompositionServiceClient(cc grpc.ClientConnInterface) PrimeNumberDecompositionServiceClient {
	return &primeNumberDecompositionServiceClient{cc}
}

func (c *primeNumberDecompositionServiceClient) PrimeNumberDecompositionStream(ctx context.Context, in *PrimeNumberDecompositionRequest, opts ...grpc.CallOption) (PrimeNumberDecompositionService_PrimeNumberDecompositionStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PrimeNumberDecompositionService_serviceDesc.Streams[0], "/primeNumberDecomposition.PrimeNumberDecompositionService/PrimeNumberDecompositionStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &primeNumberDecompositionServicePrimeNumberDecompositionStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PrimeNumberDecompositionService_PrimeNumberDecompositionStreamClient interface {
	Recv() (*PrimeNumberDecompositionResponse, error)
	grpc.ClientStream
}

type primeNumberDecompositionServicePrimeNumberDecompositionStreamClient struct {
	grpc.ClientStream
}

func (x *primeNumberDecompositionServicePrimeNumberDecompositionStreamClient) Recv() (*PrimeNumberDecompositionResponse, error) {
	m := new(PrimeNumberDecompositionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PrimeNumberDecompositionServiceServer is the server API for PrimeNumberDecompositionService service.
type PrimeNumberDecompositionServiceServer interface {
	//server streaming
	PrimeNumberDecompositionStream(*PrimeNumberDecompositionRequest, PrimeNumberDecompositionService_PrimeNumberDecompositionStreamServer) error
}

// UnimplementedPrimeNumberDecompositionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPrimeNumberDecompositionServiceServer struct {
}

func (*UnimplementedPrimeNumberDecompositionServiceServer) PrimeNumberDecompositionStream(req *PrimeNumberDecompositionRequest, srv PrimeNumberDecompositionService_PrimeNumberDecompositionStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method PrimeNumberDecompositionStream not implemented")
}

func RegisterPrimeNumberDecompositionServiceServer(s *grpc.Server, srv PrimeNumberDecompositionServiceServer) {
	s.RegisterService(&_PrimeNumberDecompositionService_serviceDesc, srv)
}

func _PrimeNumberDecompositionService_PrimeNumberDecompositionStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeNumberDecompositionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PrimeNumberDecompositionServiceServer).PrimeNumberDecompositionStream(m, &primeNumberDecompositionServicePrimeNumberDecompositionStreamServer{stream})
}

type PrimeNumberDecompositionService_PrimeNumberDecompositionStreamServer interface {
	Send(*PrimeNumberDecompositionResponse) error
	grpc.ServerStream
}

type primeNumberDecompositionServicePrimeNumberDecompositionStreamServer struct {
	grpc.ServerStream
}

func (x *primeNumberDecompositionServicePrimeNumberDecompositionStreamServer) Send(m *PrimeNumberDecompositionResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _PrimeNumberDecompositionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "primeNumberDecomposition.PrimeNumberDecompositionService",
	HandlerType: (*PrimeNumberDecompositionServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeNumberDecompositionStream",
			Handler:       _PrimeNumberDecompositionService_PrimeNumberDecompositionStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "primeNumberDecomposition.proto",
}
